# Generated by Django 2.1.2 on 2018-12-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0023_auto_20181105_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('idPrecio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(default=0.0)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Empresa')),
                ('idTipoPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.TipoPrueba')),
            ],
        ),
    ]
