# Generated by Django 2.1.2 on 2018-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArguetaServicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
