# Generated by Django 2.1.2 on 2018-12-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArguetaServicios', '0002_auto_20181214_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.TextField(max_length=5),
        ),
    ]
