# Generated by Django 2.1.2 on 2018-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArguetaServicios', '0004_auto_20181214_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
