# Generated by Django 2.1.2 on 2019-01-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArguetaServicios', '0007_auto_20181227_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('idDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('documento', models.FileField(upload_to='apempresas')),
            ],
        ),
    ]
