# Generated by Django 2.1.2 on 2018-10-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgendado', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEvaluar', models.DateField()),
                ('nombreEvaluado', models.CharField(max_length=75)),
                ('puesto', models.CharField(max_length=100)),
                ('horaProgramada', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codEmpresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('giro', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=1)),
                ('idEvaluador', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitado',
            fields=[
                ('idSolicitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrueba',
            fields=[
                ('idTipoPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPrueba', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoResultado',
            fields=[
                ('idTipoResultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Persona'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Empresa'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='idTipoPrueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.TipoPrueba'),
        ),
    ]
