# Generated by Django 2.1.2 on 2018-11-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_evaluador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=17),
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='persona',
        ),
        migrations.AddField(
            model_name='empresa',
            name='persona',
            field=models.ManyToManyField(to='recepcion.Persona'),
        ),
    ]
