# Generated by Django 2.1.2 on 2018-11-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_auto_20181102_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='idPersona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepcion.Persona'),
        ),
    ]
