# Generated by Django 2.1.2 on 2018-11-04 00:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0008_auto_20181103_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='idEmpresa',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Persona'), chained_model_field='Persona', to='recepcion.Empresa'),
        ),
    ]
