# Generated by Django 2.1.2 on 2018-11-04 01:49

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0011_auto_20181103_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='idEmpresa',
        ),
        migrations.AddField(
            model_name='agenda',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepcion.Empresa'),
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='idPersona',
        ),
        migrations.AddField(
            model_name='agenda',
            name='idPersona',
            field=smart_selects.db_fields.ChainedManyToManyField(to='recepcion.Persona'),
        ),
    ]
