# Generated by Django 2.1.2 on 2018-11-04 01:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0012_auto_20181103_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Empresa'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='idPersona',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='idEmpresa', chained_model_field='empresa', to='recepcion.Persona'),
        ),
    ]
