# Generated by Django 2.1.2 on 2018-11-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0013_auto_20181103_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='idPersona',
        ),
        migrations.AddField(
            model_name='agenda',
            name='idPersona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepcion.Persona'),
        ),
    ]
