# Generated by Django 2.1.2 on 2018-11-04 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0014_auto_20181103_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='idPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Persona'),
        ),
    ]
