# Generated by Django 2.1.2 on 2018-11-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0016_auto_20181103_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='idEmpresa',
        ),
        migrations.AddField(
            model_name='agenda',
            name='idEmpresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recepcion.Empresa'),
        ),
    ]
