# Generated by Django 2.1.2 on 2018-11-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0019_auto_20181104_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
