# Generated by Django 2.1.2 on 2018-11-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0021_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='observaciones',
            field=models.TextField(max_length=240, null=True),
        ),
    ]
