# Generated by Django 2.1.2 on 2018-11-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0022_auto_20181105_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codEmpresa',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
