# Generated by Django 2.1.2 on 2018-12-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0023_auto_20181105_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='precio',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
